rfc: retrieval research
eigerco/polka-storage pull request #623
Opened 2024-12-05 11:41 UTC by cernicc

### Description

Aggregated research about data retrieval

2024-12-05 13:58 UTC, th7nder requested changes

2024-12-05 13:58 UTC, th7nder commented on RFCs/polka-retrieval.md
> +is why for a purposes of data retrieval we also need an unsealed sector. For the
Do we? Can't we read data from the sealed sector? 

Ref:
- https://github.com/filecoin-project/rust-filecoin-proofs-api/blob/bdc9a595eba17f7fe89142b7b1fa78961bd94c50/src/seal.rs#L1406

2024-12-05 13:58 UTC, th7nder commented on RFCs/polka-retrieval.md
> +purposes of POC we expect that the unsealed sector is always available.
I think that we remove the unsealed Sector in the pipeline.

2024-12-05 13:58 UTC, th7nder commented on RFCs/polka-retrieval.md
> +### Local Index Directory
Is it the component we have already implemented?

2024-12-05 13:58 UTC, th7nder commented on RFCs/polka-retrieval.md
> +The retrieval clients enable 3rd parties to easily retrieve stored data. Good
Are we going to implement a retrieval client?

2024-12-05 13:58 UTC, th7nder commented on RFCs/polka-retrieval.md
`rfcs/002-retrieval-subsystem.md`

or something similar?

2024-12-05 13:58 UTC, th7nder commented on RFCs/polka-retrieval.md
> +This is the service that Aidan is working on. The indexer will be responsible
I think we should avoid identifiying services by ppl in RFC documents. We should just say `Indexer in RFC001` or something similar.

2024-12-05 16:02 UTC, cernicc commented on RFCs/polka-retrieval.md
> +is why for a purposes of data retrieval we also need an unsealed sector. For the
You could, but not directly. It first needs to be unsealed.

2024-12-05 16:05 UTC, cernicc commented on RFCs/polka-retrieval.md
> +### Local Index Directory
Partially. It's in `storage/polka-index`. It still needs to be integrated with the storage provider server

2024-12-05 16:12 UTC, cernicc commented on RFCs/polka-retrieval.md
> +The retrieval clients enable 3rd parties to easily retrieve stored data. Good
I think we should, at least something small like a cli app that would enable somebody to request a file from the retrieval provider.

2024-12-06 09:35 UTC, jmg-duarte requested changes
The RFC is lacking consistent writing
* References should be together and have their own section
* `cli` -> `CLI`, `cid` -> `CID`, `p2p` -> `P2P`, etc
* Don't use emphasis markers and if you MUST use, use `*` instead of `_`, it's easier to read in plaintext format

2024-12-06 09:35 UTC, jmg-duarte commented on RFCs/polka-retrieval.md
> +for holding the entire index of cids with corresponding retrieval providers. In
```suggestion
for holding the entire index of CIDs with corresponding retrieval providers. In
```

2024-12-06 09:35 UTC, jmg-duarte commented on RFCs/polka-retrieval.md
> +purposes of POC we expect that the unsealed sector is always available.
If yes, that's new, I remember discussing this and even showing that FC had a setting

2024-12-06 09:35 UTC, jmg-duarte commented on RFCs/polka-retrieval.md
> +- https://boost.filecoin.io/deployment/local-index-directory
Move resources to the bottom of the file

2024-12-06 09:35 UTC, jmg-duarte commented on RFCs/polka-retrieval.md
> +retrieval provider always have the file that the client was looking for.
```suggestion
retrieval provider always has the file that the client was looking for.
```

2024-12-06 09:35 UTC, jmg-duarte commented on RFCs/polka-retrieval.md
> +The retrieval clients enable 3rd parties to easily retrieve stored data. Good
I agree with Rok, it provides something for users to play with too

2024-12-06 09:35 UTC, jmg-duarte commented on RFCs/polka-retrieval.md
> +Each retrieval provider spins of the p2p network used to share data with clients.
This sentence doesn't make much sense. We'll discuss this off-GH & synchronously

2024-12-09 12:22 UTC, th7nder requested changes

2024-12-09 12:22 UTC, th7nder commented on rfcs/002-retrieval-subsystem.md
> +Aidan is working on. Do not confuse with the Local Index Directory) for
```suggestion
retrieval provider above. The client first queries the indexer (Do not confuse with the Local Index Directory) for
```

2024-12-09 12:22 UTC, th7nder commented on rfcs/002-retrieval-subsystem.md
> +# Polka data retrieval
I still don't know what we're proposing after reading the doc :(

2024-12-09 12:22 UTC, th7nder commented on rfcs/002-retrieval-subsystem.md
> +retrieval provider above. The client first queries the indexer (The one that
Is it querying the indexer, as we don't know whether we're implementing it still?

2024-12-11 08:46 UTC, cernicc commented on rfcs/002-retrieval-subsystem.md
> +retrieval provider above. The client first queries the indexer (The one that
The indexer holds a mapping of content_cid -> multiaddress. Unless the user provides the address manually, it needs to be queried.

2024-12-11 08:57 UTC, cernicc commented on rfcs/002-retrieval-subsystem.md
> +# Polka data retrieval
I've added the conclusion section

2024-12-11 12:02 UTC, th7nder requested changes

2024-12-11 12:02 UTC, th7nder commented on rfcs/002-retrieval-subsystem.md
> +# Polka data retrieval
```suggestion
# RFC-002 Data Retrieval
```

2024-12-11 12:02 UTC, th7nder commented on rfcs/002-retrieval-subsystem.md
> +## Retrieval client
I think the headings are not indented properly, like ### Use case, looks like should be  ## Use case.
Overall, I don't want to be mean or have it always my way, I just think the structure of this doc would need some refactoring to make it more clear to wider audiences.

E.g. I'd call `Use case` a `problem statement` .
Then, a section called: 'Solutions':
I'd specifically say what is a proposed solution, with trade-offs (using bitswap vs graphs, how to fetch CID -> mapping, on our own or via something else?), adding a additional componeent (CLI client) or stuff. 
And after that, conclusion with: Yeah, we're implementing 'Bitswap' and a separate CLI application to be able to get CIDs from Indexer (or wherever).

2024-12-12 14:28 UTC, jmg-duarte commented on RFCs/polka-retrieval.md
> +purposes of POC we expect that the unsealed sector is always available.
We've found that FC either keeps the unsealed ones or unseals them for fetching. Either way, unsealed sectors are the fetched ones

2024-12-13 11:26 UTC, cernicc commented on rfcs/002-retrieval-subsystem.md
> +## Retrieval client
I've pushed some changes regarding this. The chosen protocol with reasoning is in the Conclusion chapter. I didn't go too much into the implementation details, because many unknowns will get clearer while implementing the required components.

2024-12-13 12:33 UTC, th7nder submitted a review, later dismissed

2024-12-13 17:05 UTC, jmg-duarte reviewed
This document should cover how the actual unsealed to file process happens, asides from the LID, how can we fetch the contents from inside the unsealed sector.

The suggestions are not "apply or reject", please review and apply changes to them if you wish

2024-12-13 17:05 UTC, jmg-duarte commented on rfcs/002-data-retrieval.md
> +
Add author and date

2024-12-13 17:05 UTC, jmg-duarte commented on rfcs/002-data-retrieval.md
> +service.
```suggestion
from the storage providers. It does not cover the retrieval markets and assumes
that no additional incentives are needed for being part of the retrieval
network and that every storage provider also provides a retrieval service.
It also covers the main protocols for transfer — Bitswap and GraphSync — recommending
the implementation of Bitswap as a first instance due to the lower upfront effort required.
```

2024-12-13 17:05 UTC, jmg-duarte commented on rfcs/002-data-retrieval.md
> +service.
And even so, I believe that running a retrieval service should be required

2024-12-13 17:05 UTC, jmg-duarte commented on rfcs/002-data-retrieval.md
> +providers. To retrieve the data stored, they should provide content CID (root
Content CID is a redundancy: https://proto.school/anatomy-of-a-cid/01
```suggestion
providers. To retrieve the data stored, they should provide a CID (root
```

2024-12-13 17:05 UTC, jmg-duarte commented on rfcs/002-data-retrieval.md
> +The current server implementation exposes the endpoint which allows 3rd parties
```suggestion
The current server implementation exposes an endpoint which allows 3rd parties
```

2024-12-13 17:05 UTC, jmg-duarte commented on rfcs/002-data-retrieval.md
> +purposes of POC we expect that the unsealed sector is always available.
```suggestion
to upload some content. The content is then encoded as a CAR file; the file
is then packed into the unsealed sector, stored on disk; the unsealed
sector is sealed and stored on disk; the sealed sector is unreadable, as such
for a purposes of data retrieval, we either keep the unsealed sector around at the cost of storage capacity or unseal sectors on-demand — for the
purposes of POC we expect that the unsealed sector is always available.
```

2024-12-13 17:05 UTC, jmg-duarte commented on rfcs/002-data-retrieval.md
> +file.
```suggestion
subsystem. Sectors are opaque, meaning they don't contain metadata that indicates where its files start and end,
that is where the index enters, mapping the sector and enabling retrieval of individual files.
```

2024-12-13 17:05 UTC, jmg-duarte commented on rfcs/002-data-retrieval.md
> +where exactly is that data located in the sector.
There's no need to repeat that the LID is used to find the sectors

```suggestion
The retrieval process requires access to the local index and the unsealed sectors, thus, 
it must be co-located with the storage process.
```

2024-12-13 17:05 UTC, jmg-duarte commented on rfcs/002-data-retrieval.md
> +retrieval provider always has the file that the client was looking for.
```suggestion
Bitswap is used to exchange blocks of data between peers. In short, it works
on a "question and answer" basis, where the client request the data for a given CID and
the server replies with that data, be it more CIDs or an actual block of data.
When coupled with IPLD graphs, this approach becomes "chatty" for large files; 
since the first rounds of the protocol will usually consist of requesting a CID and getting N CIDs back,
requesting each of those CIDs and getting more back, until reaching actual data blocks.
```

2024-12-13 17:05 UTC, jmg-duarte commented on rfcs/002-data-retrieval.md
> +number of independent requests.
A more detailed explanation of the protocol would be a great addition, especially covering why it eventually supersedes Bitswap

2024-12-13 17:05 UTC, jmg-duarte commented on rfcs/002-data-retrieval.md
> +http server.
```suggestion
example of the retrieval client is Lassie which can be used as a CLI, library or
HTTP server.
```

2024-12-13 17:05 UTC, jmg-duarte commented on rfcs/002-data-retrieval.md
> +retrieval provider above. The client first queries the indexer (Do not confuse
```suggestion
retrieval provider above. The client first queries the indexer (do not confuse
```

2024-12-13 17:05 UTC, jmg-duarte commented on rfcs/002-data-retrieval.md
> +for data transfer between peers: Bitswap and GraphSync.
```suggestion
This document covered the key technical challenge when implementing retrievals for a system like Polka Storage,
as well as the main contenders for the retrieval protocol — Bitswap and GraphSync.
```

2024-12-16 17:30 UTC, jmg-duarte approved these changes, later dismissed
Nits

2024-12-16 17:30 UTC, jmg-duarte commented on rfcs/002-data-retrieval.md
> +We would like to support 3rd parties to retrieve data from the storage
```suggestion
We would like to enable 3rd parties to retrieve data from the storage
```

2024-12-16 17:30 UTC, jmg-duarte commented on rfcs/002-data-retrieval.md
> +providers. To retrieve the data stored, they should provide payload CID (root
```suggestion
providers. To retrieve the data stored, they should provide the payload CID (root
```

2024-12-16 17:30 UTC, jmg-duarte commented on rfcs/002-data-retrieval.md
> +we expect that the unsealed sector is always available.
```suggestion
we expect the unsealed sector to always be available.
```

2024-12-16 17:30 UTC, jmg-duarte commented on rfcs/002-data-retrieval.md
> +It is used to synchronize graphs across peers. It uses IPLD selector to
```suggestion
It is used to synchronize graphs across peers. It uses IPLD selectors to
```

2024-12-16 17:30 UTC, jmg-duarte commented on rfcs/002-data-retrieval.md
> +number of independent requests. It supersedes the Bitswap, because the client
```suggestion
number of independent requests. It supersedes Bitswap, because the client
```

2024-12-16 17:30 UTC, jmg-duarte commented on rfcs/002-data-retrieval.md
> +The retrieval clients enable 3rd parties to easily retrieve stored data. Good
```suggestion
The retrieval clients enable 3rd parties to easily retrieve stored data. A good
```

2024-12-16 17:30 UTC, jmg-duarte commented on rfcs/002-data-retrieval.md
> +After it receives 1 or more candidates it sends a retrieval request to those
It may be confused with an L in some fonts, this way is clearer
```suggestion
After it receives one or more candidates it sends a retrieval request to those
```

2024-12-16 17:30 UTC, jmg-duarte commented on rfcs/002-data-retrieval.md
> +- https://github.com/filecoin-project/lassie
As is, this is just a collection of links, ideally we have bits of text leading to link itself

2024-12-17 09:56 UTC, jmg-duarte approved these changes

2024-12-17 10:45 UTC, th7nder approved these changes

2024-12-17 10:45 UTC, merged