rfc: Add RFC for libp2p resolver
eigerco/polka-storage pull request #629
Opened 2024-12-09 09:18 UTC by aidan46

### Description

This PR adds an RFC for the libp2p Peer ID to multiaddr resolver. This application will be used by clients to find the multiaddr associated with a Peer ID of a deal to fetch the file from the storage provider (using the polka-fetch component) I followed the guidelines described in [rfc7322](https://www.rfc-editor.org/rfc/rfc7322). 

A follow-up PR will be created for the scraper that collects on-chain information about deals (both historical and current).

2024-12-09 09:48 UTC, jmg-duarte commented on rfcs/001-libp2p-resolver.md
> +Clients need to resolve [Peer ID][5]s to [multi-addresses][4] do they can connect to storage providers and fetch their files. File fetching will not be covered in this document.
More general + more accurate (since you can send a status request)
```suggestion
Clients need to resolve [Peer ID][5]s to [multi-addresses][4] so they can connect to and communicate with storage providers.
```

2024-12-09 09:48 UTC, jmg-duarte commented on rfcs/001-libp2p-resolver.md
> +Storage providers have a incentive to run bootstrap nodes in the P2P network because it enhances their trustworthiness and visibility within the ecosystem.
Running a bootstrap node doesn't make you more trustworthy, it's just perception. Correctly handling deals makes you trustworthy!
```suggestion
Storage providers have a incentive to run bootstrap nodes in the P2P network because it increases their perceived trustworthiness and visibility within the ecosystem.
```

2024-12-09 09:48 UTC, jmg-duarte commented on rfcs/001-libp2p-resolver.md
> +Trust is critical factor for storage clients selecting which storage provider to store their data.
Note: we don't have a trust/reputation mechanism, as such we need to be careful with our wording. I'm not sure that removing this line would make it better but I'm also not sure it should be kept as is
```suggestion
Trust is a critical factor for storage clients selecting which storage provider to store their data.
```

2024-12-09 09:48 UTC, jmg-duarte commented on rfcs/001-libp2p-resolver.md
> +Bootstrap nodes and contribute to a more seamless client experience by helping ensure that content can be discovered and retrieved efficiently.
```suggestion
Bootstrap nodes are required for a seamless client experience by helping ensure that content can be discovered and retrieved efficiently.
```

2024-12-09 09:48 UTC, jmg-duarte commented on rfcs/001-libp2p-resolver.md
> +The CLI tool will be distributed as a single executable binary, ensuring ease of deployment across diverse platforms and environments.
I don't think this is relevant, IMO the RFC is to discuss the high-level ideas; CLI, single or multiple binaries, etc, those are implementation details.

https://github.com/eigerco/polka-storage/pull/629/files#diff-96ebdac0b36633969fe397b19ef41c994f26b798a7bff824a8ca1f5486aa0f7eR22

This line can almost be thought of as the border, it states that the final product should be configurable, provides and example, but it doesn't really commit to anything

2024-12-09 12:14 UTC, th7nder requested changes

2024-12-09 12:14 UTC, th7nder commented on rfcs/001-libp2p-resolver.md
> +This RFC proposes an application for resolving [Peer ID][5]s to [multi-addresses][4] in a [libp2p][1] network.
Why do we need a separate application for that? Shouldn't it be a part of file retrieval or something similar?

2024-12-10 04:49 UTC, aidan46 commented on rfcs/001-libp2p-resolver.md
> +This RFC proposes an application for resolving [Peer ID][5]s to [multi-addresses][4] in a [libp2p][1] network.
IMO, the file retrieval interface should be a bit simpler for the end-user, they don't care about peer ID resolver if they already have the multiaddr, they just want to retrieve their file with the multiaddr and the CID. This application should be written so the retriever can use the functionality to resolve the multiaddr from the peer ID.

2024-12-11 09:07 UTC, th7nder commented on rfcs/001-libp2p-resolver.md
> +This RFC proposes an application for resolving [Peer ID][5]s to [multi-addresses][4] in a [libp2p][1] network.
So we're proposing a `library` or an standalone application for resolving PeerIDs?
So this libp2p resolver will be a separate system process?

2024-12-13 17:08 UTC, jmg-duarte commented
Should this RFC discuss Kademlia too?

2024-12-16 09:18 UTC, aidan46 commented
> Should this RFC discuss Kademlia too?

We talked about moving forward with the rendezvous protocol. If we notice that the rendezvous protocol does not scale well we can move to Kademlia after creating an RFC for the upgrade.

2024-12-16 17:23 UTC, jmg-duarte submitted a review, later dismissed

2024-12-16 17:25 UTC, jmg-duarte commented on rfcs/001-libp2p-resolver.md
> +
You're missing the author + date

2024-12-17 09:42 UTC, jmg-duarte approved these changes

2024-12-17 12:22 UTC, th7nder approved these changes

2024-12-17 12:22 UTC, merged