feat: Add peer-resolver lib
eigerco/polka-storage pull request #640
Opened 2024-12-17 10:50 UTC by aidan46

### Description

Add the peer-resolver library with bootstrap and client nodes using the rendezvous protocol for peer discovery. Examples for bootstrap, registration and discovery have been added.

2024-12-18 11:32 UTC, jmg-duarte reviewed
Preliminary remarks, good job on figuring this out! 🚀

2024-12-18 11:32 UTC, jmg-duarte commented on lib/peer-resolver/README.md
Line breaks, please

2024-12-18 11:32 UTC, jmg-duarte commented on lib/peer-resolver/src/client.rs
> +pub struct ClientSwarm {
`ClientSwarm` is super generic
```suggestion
pub struct RendezvousClientSwarm {
```

2024-12-18 11:32 UTC, jmg-duarte commented on lib/peer-resolver/examples/discovery.rs
For an example, this is lacking on the "how and why" department. Can you add more comments explaining the code, almost step by step?

2024-12-18 11:32 UTC, jmg-duarte commented on lib/peer-resolver/examples/discovery.rs
> +                        tracing::info!("Connected to rendezvous point, discovering nodes");
```suggestion
                        tracing::info!("Connection established with rendezvous point {peer_id}, discovering nodes...");
```

2024-12-18 11:32 UTC, jmg-duarte commented on lib/peer-resolver/src/bootstrap.rs
> +                _other => {}
Shouldn't we do at least a debug log?

2024-12-20 10:36 UTC, jmg-duarte reviewed
One question I have is — what is a cookie in this context?

2024-12-20 10:36 UTC, jmg-duarte commented on lib/peer-resolver/src/discovery.rs
> +    pub fn new<K>(keypair_bytes: K, timeout: u64) -> Result<DiscoverySwarm, ResolverError>
Timeout should be a `Duration`

2024-12-20 10:36 UTC, jmg-duarte commented on lib/peer-resolver/src/discovery.rs
> +    pub fn discover(&mut self, rendezvous_point: PeerId) {
I'm not sure this function name is good, it isn't really descriptive of what it does. 
I know it wraps `discover` but I'm not convinced by libp2p's naming.

2024-12-20 10:36 UTC, jmg-duarte commented on lib/peer-resolver/src/register.rs
> +    pub async fn register(
Docs

2024-12-20 10:36 UTC, jmg-duarte commented on lib/peer-resolver/src/register.rs
> +    pub async fn unregister(&mut self, rendezvous_point: PeerId) {
Docs

2024-12-20 10:36 UTC, jmg-duarte commented on lib/peer-resolver/src/register.rs
> +pub struct RegisterSwarm {
Docs

2024-12-20 10:36 UTC, jmg-duarte commented on lib/peer-resolver/examples/identify.rs
> +        .await?;
Does this simply "stay on"? In other words, when does this function call exit?

2024-12-20 11:06 UTC, aidan46 commented
> One question I have is — what is a cookie in this context?

A cookie is passed into the discover function to only receive peers that have changed or joined since the last discover message was served.

2024-12-20 11:09 UTC, aidan46 commented on lib/peer-resolver/examples/identify.rs
> +        .await?;
This function call exits as soon as the peer is registered. The peer knows this when it receives the `Registered` event from the rendezvous point.

2024-12-20 11:09 UTC, cernicc reviewed
Try to create a single example of using all these behaviors and you'll see how do you like the usage of the current abstraction.

2024-12-20 11:56 UTC, th7nder requested changes

2024-12-20 11:56 UTC, th7nder commented on lib/peer-resolver/README.md
> +This library is intended for peer discovery in a libp2p network.
Could you remind me what is the expected usage of this library in our storage solution? 
It's kinda hard to imagine for me whether those abstractions are correct, if we write the library first and the usage second.
This looks like a nice example, but not sure whether it will fit/how it will fit in our whole system.

2024-12-20 11:56 UTC, th7nder commented on lib/peer-resolver/src/bootstrap.rs
> +                    "rendezvous-example/1.0.0".to_string(),
Why `rendevous-example/1.0.0`, what is it supposed to mean?

2024-12-20 12:09 UTC, aidan46 commented on lib/peer-resolver/src/bootstrap.rs
> +                    "rendezvous-example/1.0.0".to_string(),
This is the protocol information it shares with peers. It should not be rendezvous-example, even though we do not use this, this is an oversight on my end.

2024-12-20 12:10 UTC, aidan46 commented on lib/peer-resolver/src/bootstrap.rs
> +                    "rendezvous-example/1.0.0".to_string(),
This is the protocol information it shares with peers. It should not be rendezvous-example, even though we do not use this, this is an oversight on my end.

2024-12-27 05:50 UTC, closed without merging