feat(pallet-randomness): add benchmarks
eigerco/polka-storage pull request #657
Opened 2024-12-23 16:16 UTC by jmg-duarte

### Description

Adds benchmarks for the proofs pallet

2025-01-02 16:50 UTC, th7nder requested changes

2025-01-02 16:50 UTC, th7nder commented on runtime/src/configs/mod.rs
> +    type WeightInfo = pallet_randomness::weights::Weights<Runtime>;
That's funny, weren't the weights set before for pallet randomness?
And the PR title says pallet randomness, I think it's for pallet proofs.

2025-01-02 16:50 UTC, th7nder commented on pallets/weights.rs
looks like an unnecessary file

2025-01-02 16:56 UTC, jmg-duarte commented on runtime/src/configs/mod.rs
> +    type WeightInfo = pallet_randomness::weights::Weights<Runtime>;
extra file too

2025-01-02 17:02 UTC, th7nder approved these changes

2025-01-03 09:38 UTC, cernicc approved these changes

2025-01-03 09:38 UTC, merged